locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
    path('quiz/', include('quiz.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='quiz-index'),
    path('questions/', views.QuestionListView.as_view(), name="questions"),
    path('contact/', views.ContactFormView.as_view(), name="contact"),
    path('quiz_result/', views.quiz_result, name="quiz-result"),
    path('csv/', views.get_answer_sheet_csv, name="get-csv"),
]

quiz/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

    @property
    def get_correct_answer(self):
        return self.set_choices.get(is_correct_answer=True)

class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE,
                                 related_name='set_choices')
    choice_text = models.CharField(max_length=50)
    is_correct_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

# ---------------------------

quiz/forms.py
from django import forms
from django.forms import CheckboxInput

from .models import Question

class QuizForm(forms.ModelForm):
    """
    Model form for quiz
    """
    class Meta:
        model = Question
        fields = ['question_text']

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

quiz/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Question, Choice
from .forms import QuizForm, ContactForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
import csv


class IndexView(TemplateView):
    """
    Template View for quiz index (Home) page
    """
    template_name = "quiz_index.html"

class QuestionListView(generic.ListView):
    """
    Question List View page
    return : all questions of question model
    """
    template_name = 'quiz/Question_list.html'
    context_object_name = 'all_question'

    def get_queryset(self):
        return Question.objects.all().order_by("pub_date")

def quiz_result(request):
    """
    return: score of quiz
    """
    if request.method == 'POST':

        # To implement the session data
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1

        score = 0

        # The first item in the post is csrf token
        request_post_items = list(request.POST.items())
        question_choice_list = request_post_items[1:]

        for each in question_choice_list:

            # get the id & object
            question = Question.objects.get(question_text__exact=each[0])
            selected_choices = Choice.objects.get(pk=each[1])

            if selected_choices == question.get_correct_answer:
                score += 1

        result = {'score': score,
                  'num_visits': num_visits,
                  }
        return render(request, 'quiz/quiz_result.html', context=result)

    return render(request, 'quiz_index.html')

class ContactFormView(FormView):
    """
    class base view for the FormerView
    """
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/catalog/thanks/'

def get_answer_sheet_csv(request):
    """
    Generate the answer sheet csv file
    """
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Answer sheet.csv"'

    questions = Question.objects.all()

    header = ['Questions', 'Answers']

    writer = csv.DictWriter(response, fieldnames=header)
    writer.writeheader()

    writer = csv.writer(response)
    for question in questions:
        correct_answer = question.get_correct_answer
        writer.writerow([question.question_text, correct_answer])
    return response

quiz/templates/quiz/Question_list.html
<!DOCYTPE html>
<html>
<head>
    <title>Question's</title>
    {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/question_list.css' %}">
</head>

<body>
<form action="{% url 'quiz:quiz-result' %}" method="post">
    {% csrf_token %}
    <center><h1>Online Quiz System</h1></center>
    <center><h2>MCQ Base Test</h2></center>
        <ul>
        {% for question in all_question %}
        <li>{{ forloop.counter }} {{ question }}</li>
        <ul>
            {% for choice in question.set_choices.all %}
            <input type="radio" name="{{question}}" id="choice {{ forloop.counter }}}"
                   value={{ choice.id }}></input>
            <lable>{{ choice }}</lable>
            <br>
            {% endfor %}
        </ul>
            <hr>
        <br>
        {% endfor %}
    </ul>
    <input type="submit" value="submit">
</form>
</body>
</html>

quiz/templates/quiz/quiz_result.html
{% extends "base_generic.html" %}

{% block content %}
  {% if user.is_authenticated %}
  <h2>Thank you {{ user.get_username }} for participating </h2>
  <h5>Your Score {{ score }}</h5>
  <h5>Num _init {{ num_init }}</h5>

<h5>Session-->{{num_visits}}</h5>
  <br>
  <br>
  <h4>Download the Answer sheet here</h4>
  <a href="/quiz/csv">Download</a>

  {% else %}
  <h2>Thank you for participating in Library Quiz </h2>
  <h3>Click here to be a permanent member</h3>
  <h5>Your Score {{ score }}</h5>
  {% endif %}

{% endblock %}