catalog/urls.py
from django.urls import path
from . import views
from django.views.generic.dates import ArchiveIndexView
from .models import Author

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('get_name/', views.GetNameView.as_view(), name='name'),
    path('author/', views.AuthorListView.as_view(), name='author'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='detail_author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('feedback/', views.feedback, name='feedback'),
    path('Dellogin/', views.Dellogin, name='Dellogin'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('add_venue/', views.FeedbackFormView.as_view(), name='add-venue'),
    path('create_auth/', views.AuthorCreateView.as_view(), name='create-auth'),
    path('update_auth/<int:pk>/', views.AuthorUpdateView.as_view(), name='update-auth'),
    path('delete_auth/<int:pk>/', views.AuthorDeleteView.as_view(), name='delete-auth'),
    path('archive/',ArchiveIndexView.as_view(model=Author, date_field="date_of_birth"),
         name="article_archive"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
    path('quiz/', include('quiz.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='quiz-index'),
    path('questions/', views.QuestionListView.as_view(), name="questions"),
    path('contact/', views.ContactFormView.as_view(), name="contact"),
    path('quiz_result/', views.quiz_result, name="quiz-result"),
    path('csv/', views.get_answer_sheet_csv, name="get-csv"),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                             help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('detail_author', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Venue(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_number = models.CharField(max_length=10, null=True, blank=True)

catalog/forms.py
from django import forms
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import Venue


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    lib_id = forms.CharField(label="Library ID")
    class_name = forms.IntegerField(label="Class")
    roll_no = forms.IntegerField(label="Roll No.")
    log_pass = forms.CharField(widget=forms.PasswordInput())


class FeedBackForm(forms.Form):
    your_name = forms.CharField(label="Your Name")
    email_id = forms.EmailField(label="Email Id", required=False)
    contact_number = forms.CharField(label="Contact number", required=False, max_length=10)
    birth_date = forms.DateField(widget=forms.SelectDateWidget())
    Rating = forms.IntegerField(label="Rating", required=False)
    suggestion = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(FeedBackForm, self).__init__(*args, **kwargs)

        self.fields['your_name'].widget.attrs['placeholder'] = 'Full Name'
        self.fields['suggestion'].widget.attrs['placeholder'] = 'Suggestion.....'
        self.fields['Rating'].widget.attrs['placeholder'] = '*****'
        self.fields['email_id'].widget.attrs['placeholder'] = 'abc@gmail.com'
        self.fields['contact_number'].widget.attrs['placeholder'] = 'Mobile Number'


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(VenueForm, self).__init__(*args, **kwargs)

        # self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        # self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        # self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        # self.fields['contact_number'].widget.attrs['placeholder'] = 'Mobile Number'

        # Assigning class and placeholder to form element
        self.fields['first_name'] = forms.EmailField(label=_("First Name"),
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class':'first_name'}))
        self.fields['last_name'] = forms.EmailField(label=_("Last Name"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Last Name', 'class': 'last_name'}))
        self.fields['email'] = forms.EmailField(label=_("E-mail"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Your Email', 'class': 'email'}))
        self.fields['contact_number'] = forms.EmailField(label=_("Contact Number"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Contact number', 'class': 'contact_number'}))

catalog/views.py
from django.shortcuts import render
from .forms import NameForm
from .models import Book, Author, BookInstance
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.views.generic import View
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .forms import RenewBookForm, FeedBackForm, VenueForm
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from datetime import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy



class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        # Generate counts of some of the main objects
        context['num_books'] = Book.objects.all().count()
        context['num_instances'] = BookInstance.objects.all().count()
        context['num_instances_available'] = BookInstance.objects.filter(status__exact='a').count()
        context['num_authors'] = Author.objects.count()

        return context


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)
        return render(request, 'catalog/book_detail.html', context={'book': book})


class GetNameView(View):
    template_name = 'name.html'
    form_class = NameForm

    def get(self, request, template_name=template_name, *args, **kwargs):
        form = self.form_class
        return render(request, template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # form.save()
            # return HttpResonseRedirect(reverse('list-view'))
            return HttpResponse('/thanks/')
        else:
            return render(request, self.template_name, {'form': form})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            ref_book = book_instance.book.id
            print("Refr to -->", ref_book)

            book = Book.objects.get(pk=ref_book)
            print("book-->", book)

            ref_book_all_instance = book.bookinstance_set.all()
            print("ref_book_all_instance-->", ref_book_all_instance)

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('index'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorListView(generic.ListView):
    template_name = 'catalog/author.html'
    context_object_name = 'all_author'

    def get_queryset(self):
        all_author = Author.objects.all()

        return all_author


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_author_detail(request, primary_key):
        author = get_object_or_404(Author, pk=primary_key)
        return render(request, 'author_detail.html', context={'author': author})


@login_required
def feedback(request):
    """
    Fun for the django Form feedback handling
    """
    submitted = False
    if request.method == 'POST':
        form = FeedBackForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # assert False
            return HttpResponseRedirect(reverse('thanks'))
        # form = FeedBackForm()
        # if 'submitted' in request.GET:
        #     submitted = True

    else:
        form = FeedBackForm(request.GET)

    context = {
        'form': form,
    }
    return render(request, 'feedback.html', context)

class ThanksView(TemplateView):
    """
    return Thanks Template
    """
    template_name = "thanks.html"

class FeedbackFormView(LoginRequiredMixin, View):
    template_name = 'add_venue.html'

    def get(self, request, template_name=template_name, *args, **kwargs):
        form = VenueForm()
        submitted = False
        if 'submitted' in request.GET:
            submitted = True
        return render(request, template_name, {'form': form,
                                               'submitted': submitted})

    def post(self, request, *args, **kwargs):
        form = VenueForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/catalog/add_venue/?submitted=True')
        else:
            return HttpResponse("Form data is invalid****")

class AuthorCreateView(CreateView):
    model = Author
    fields = ['first_name', 'last_name']


class AuthorUpdateView(UpdateView):
    model = Author
    fields = ['first_name', 'last_name']
    template_name_suffix = '_update_form'


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('')

def Dellogin(request):
    return render(request, 'login_page.html')

catalog/templates/add_venue.html
  {% extends "base_generic.html" %}

  {% block title %}<title>Add Venue</title>{% endblock title %}
  {% load static %}


  {% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/venue_styles1.css' %}">
  {% endblock %}

  {% block content %}
  <h2>Fill up the following details we will contact you Shortly</h2>
  <br>
  {% if submitted %}
  <p class="success">
     Your Request is submitted successfully. We will contact you Shortly <br><br> Thank you.
   </p>
 {% else %}
   <form action="" method="post" novalidate>
   <table>
     {{ form.as_table }}
     <tr>
       <td>&nbsp;</td>
       <td><input type="submit" value="Submit"></td>
     </tr>
   </table>
   {% csrf_token %}
   </form>
 {% endif %}
 {% endblock content %}

catalog/templates/author_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Load icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books' %}">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'author' %}">Authors</a>
                </li>
            </ul>

            <input type="text" placeholder="Search Books" name="search">
            <button type="submit"><i class="fa fa-search"></i></button>

            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#"><i class="fas fa-user"></i> Sign Up</a></li>

                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}"><i class="fas fa-sign-in-alt"></i>
                    Login</a></li>
                {%endif%}

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}"><i class="fas fa-sign-in-alt"></i>
                    Logout</a></li>
                {%endif%}

            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="jumbotron">
        <h1>Digital Library</h1>
        <pre>
        Traditionally, collection of books
            used for reading or study.
            {% if user.is_authenticated %}
            <h2>Welcome: {{ user.get_username }}</h2>
            {%endif%}
        </pre>
    </div>
</div>
<div class="sidenav">
    <a href="{% url 'quiz:quiz-index' %}">Play Quiz</a>
    <a href="{% url 'feedback' %}">Feedback</a>
    <a href="{% url 'add-venue' %}">Contact Us</a>
</div>
<div class="col-sm-10">{% block content %}{% endblock %}</div>


<!--<nav aria-label="Page navigation example">-->
<!--  <ul class="pagination">-->
<!--    <li class="page-item"><a class="page-link" href="#">Previous</a></li>-->
<!--    <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--    <li class="page-item"><a class="page-link" href="#">2</a></li>-->
<!--    <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--    <li class="page-item"><a class="page-link" href="#">Next</a></li>-->
<!--  </ul>-->
<!--</nav>-->

<div class="pagination">
    {% block pagination %}
    {% if is_paginated %}
    <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
    </span>
    </div>
    {% endif %}
    {% endblock %}
</div>

</body>

</html>

catalog/templates/feedback.html
{% extends "base_generic.html" %}

{% block title %}<title>Feedback</title>{% endblock %}

{% block extra_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/feedback_form1.css' %}">
{%endblock%}


{% block content %}
  <form action="" method="post">
    {% csrf_token %}
`    <table>
    {{ form.as_table }}
    </table>`
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Home</title>{% endblock %}

{% block content %}
<h1>Manage Library</h1>
<br>
<h3>Current library statement</h3>

<br>

<p>Library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>
{% endblock %}

catalog/templates/js_practice.html
<!DOCTYPE html>
<html>
<body>

  <script>
      let user = {
      name: "John",
      sizes: {
        height: 182,
        width: 50
      }
    };

    let clone = Object.assign({}, user);

    alert( user.sizes === clone.sizes ); // true, same object

    // user and clone share sizes
    user.sizes.width++;       // change a property from one place
    alert(clone.sizes.width); // 51, see the result from the other one
  </script>

</body>
</html>

catalog/templates/login_page.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/login_page.css' %}">
        {% comment %} <link rel="stylesheet" href="catalog/static/css/login.css"> {% endcomment %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Admin Site log-in</h1>
        <form method="post">
            <lable>Name:</lable>
            <input type=text placeholder="Enter user name" name="user_name" required>
            <lable>Password</lable>
            <input type="Password" placeholder="Enter Password" name="password" required>
            <button type="submit" value="submit">Submit</button>
            <button type="button" class="cancelbtn"> Cancel</button>
        </form>
        
        <script src="" async defer></script>
    </body>
</html>

catalog/templates/name.html
<form action="" method="post">
    {% csrf_token %}
    <h1>Library Login page</h1>

    {% for element in form %}
    <table>
        <tr>
            <td>{{ element.label_tag }}</td>
            <td>{{ element }}</td>
        </tr>
    </table>
    {% endfor %}

    <input type="submit" value="Submit">
</form>

catalog/templates/thanks.html
{% extends "base_generic.html" %}
 {% block content %}
 <h2>Thanks !!!!!!!</h2>
 {% endblock %}