catalog/urls.py
from django.urls import path
from . import views
from django.views.generic.dates import ArchiveIndexView
from .models import Author

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('get_name/', views.GetNameView.as_view(), name='name'),
    path('author/', views.AuthorListView.as_view(), name='author'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='detail_author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('feedback/', views.feedback, name='feedback'),
    path('Dellogin/', views.Dellogin, name='Dellogin'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('add_venue/', views.FeedbackFormView.as_view(), name='add-venue'),
    path('create_auth/', views.AuthorCreateView.as_view(), name='create-auth'),
    path('update_auth/<int:pk>/', views.AuthorUpdateView.as_view(), name='update-auth'),
    path('delete_auth/<int:pk>/', views.AuthorDeleteView.as_view(), name='delete-auth'),
    path('archive/',ArchiveIndexView.as_view(model=Author, date_field="date_of_birth"),
         name="article_archive"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
    path('quiz/', include('quiz.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='quiz-index'),
    path('questions/', views.QuestionListView.as_view(), name="questions"),
    path('contact/', views.ContactFormView.as_view(), name="contact"),
    path('quiz_result/', views.quiz_result, name="quiz-result"),
    path('csv/', views.get_answer_sheet_csv, name="get-csv"),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                             help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('detail_author', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Venue(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_number = models.CharField(max_length=10, null=True, blank=True)

catalog/forms.py
from django import forms
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import Venue


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    lib_id = forms.CharField(label="Library ID")
    class_name = forms.IntegerField(label="Class")
    roll_no = forms.IntegerField(label="Roll No.")
    log_pass = forms.CharField(widget=forms.PasswordInput())


class FeedBackForm(forms.Form):
    your_name = forms.CharField(label="Your Name")
    email_id = forms.EmailField(label="Email Id", required=False)
    contact_number = forms.CharField(label="Contact number", required=False, max_length=10)
    birth_date = forms.DateField(widget=forms.SelectDateWidget())
    Rating = forms.IntegerField(label="Rating", required=False)
    suggestion = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(FeedBackForm, self).__init__(*args, **kwargs)

        self.fields['your_name'].widget.attrs['placeholder'] = 'Full Name'
        self.fields['suggestion'].widget.attrs['placeholder'] = 'Suggestion.....'
        self.fields['Rating'].widget.attrs['placeholder'] = '*****'
        self.fields['email_id'].widget.attrs['placeholder'] = 'abc@gmail.com'
        self.fields['contact_number'].widget.attrs['placeholder'] = 'Mobile Number'


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(VenueForm, self).__init__(*args, **kwargs)

        # self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        # self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        # self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        # self.fields['contact_number'].widget.attrs['placeholder'] = 'Mobile Number'

        # Assigning class and placeholder to form element
        self.fields['first_name'] = forms.EmailField(label=_("First Name"),
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class':'first_name'}))
        self.fields['last_name'] = forms.EmailField(label=_("Last Name"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Last Name', 'class': 'last_name'}))
        self.fields['email'] = forms.EmailField(label=_("E-mail"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Your Email', 'class': 'email'}))
        self.fields['contact_number'] = forms.EmailField(label=_("Contact Number"),
                                                widget=forms.TextInput(
                                                    attrs={'placeholder': 'Contact number', 'class': 'contact_number'}))

catalog/views.py
from django.shortcuts import render
from .forms import NameForm
from .models import Book, Author, BookInstance
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.views.generic import View
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .forms import RenewBookForm, FeedBackForm, VenueForm
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from datetime import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy



class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        # Generate counts of some of the main objects
        context['num_books'] = Book.objects.all().count()
        context['num_instances'] = BookInstance.objects.all().count()
        context['num_instances_available'] = BookInstance.objects.filter(status__exact='a').count()
        context['num_authors'] = Author.objects.count()

        return context


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)
        return render(request, 'catalog/book_detail.html', context={'book': book})


class GetNameView(View):
    template_name = 'name.html'
    form_class = NameForm

    def get(self, request, template_name=template_name, *args, **kwargs):
        form = self.form_class
        return render(request, template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # form.save()
            # return HttpResonseRedirect(reverse('list-view'))
            return HttpResponse('/thanks/')
        else:
            return render(request, self.template_name, {'form': form})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            ref_book = book_instance.book.id
            print("Refr to -->", ref_book)

            book = Book.objects.get(pk=ref_book)
            print("book-->", book)

            ref_book_all_instance = book.bookinstance_set.all()
            print("ref_book_all_instance-->", ref_book_all_instance)

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('index'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorListView(generic.ListView):
    template_name = 'catalog/author.html'
    context_object_name = 'all_author'

    def get_queryset(self):
        all_author = Author.objects.all()

        return all_author


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_author_detail(request, primary_key):
        author = get_object_or_404(Author, pk=primary_key)
        return render(request, 'author_detail.html', context={'author': author})


@login_required
def feedback(request):
    """
    Fun for the django Form feedback handling
    """
    submitted = False
    if request.method == 'POST':
        form = FeedBackForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # assert False
            return HttpResponseRedirect(reverse('thanks'))
        # form = FeedBackForm()
        # if 'submitted' in request.GET:
        #     submitted = True

    else:
        form = FeedBackForm(request.GET)

    context = {
        'form': form,
    }
    return render(request, 'feedback.html', context)

class ThanksView(TemplateView):
    """
    return Thanks Template
    """
    template_name = "thanks.html"

class FeedbackFormView(LoginRequiredMixin, View):
    template_name = 'add_venue.html'

    def get(self, request, template_name=template_name, *args, **kwargs):
        form = VenueForm()
        submitted = False
        if 'submitted' in request.GET:
            submitted = True
        return render(request, template_name, {'form': form,
                                               'submitted': submitted})

    def post(self, request, *args, **kwargs):
        form = VenueForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/catalog/add_venue/?submitted=True')
        else:
            return HttpResponse("Form data is invalid****")

class AuthorCreateView(CreateView):
    model = Author
    fields = ['first_name', 'last_name']


class AuthorUpdateView(UpdateView):
    model = Author
    fields = ['first_name', 'last_name']
    template_name_suffix = '_update_form'


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('')

def Dellogin(request):
    return render(request, 'login_page.html')

catalog/templates/catalog/author.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author List:</h1>
<table class="table table-dark table-sm">
    <tr>
        <th>Author Name</th>
    </tr>
    {% for author in all_author %}
    <tr>
        <td><a href="{{ author.get_absolute_url }}">{{ author }}</a></td>
    </tr>
    {% endfor %}

</table>

{% endblock %}

catalog/templates/catalog/author_archive.html
<ul>
    {% for author in latest %}
        <li>{{ author.first_name }}: {{ article.date_of_birth }}</li>
    {% endfor %}
</ul>

catalog/templates/catalog/author_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author Detail:</h1>
    {% if author %}
        <p>This is the detail page of author:{{ author }}</p>
        {% for book in author.book_set.all %}
        <ul>
            <li>
                {{ book.title }}
            </li>
        </ul>
        {% endfor %}
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Author</title>
  </head>
  <body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
    </form>
  </body>
  <input type="submit" value="submit">
</html>

catalog/templates/catalog/author_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    {% if request.user.is_authenticated %}
    <a href="{% url 'renew-book-librarian' copy.id %}"><button style="font-size:12px">Re-new</button></a>
    {% endif %}
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}

<table class="table table-dark table-sm">
    <tr>
        <th>Book Name</th>
        <th>Author</th>
    </tr>
    {% for book in book_list %}
    <tr>
        <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
        <td>{{book.author}}</td>
    </tr>
    {% endfor %}
{%endif%}

    {%endblock%}
</table>

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"
{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>

{% if bookinstance_list %}
<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
    </li>
    {% endfor %}
</ul>

{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}